### ISSUE TITLE
complie the source failed

### ISSUE THREAD

**Issue by gugu-lee** [chunyeow/openairinterface5g#5]
i want to try complie the source but failed.
fatal error:S1ap-Criticality.h :no such file or directory.
how resolve it?

**Comment by chunyeow** [comment]
Which source that you used? Perhaps, go for gitlab to get the latest branch.

**Comment by gugu-lee** [comment]
thx ,i cloned the last develope branch,and complie it ok.
thx ,but now i happen some other problem ,i am try to make it well.

**Comment by psurampudi** [comment]
Hi,
I just downloaded the openair-cn code from the master branch and tried compiling mme using build_mme script and am facing the same issue saying "S1ap-Criticality.h: No such file or directory".
Can you please let me know the branch from which the source code needs to be picked up from?
Thanks in advance!

**Comment by chunyeow** [comment]
Try to refer the docs file in the repo. There is a lot of changes happening
on openair-cn these days.
